### ISSUE TITLE
List Of Issues

### ISSUE THREAD

**Issue by goerick** [NiclasOlofsson/MiNET#25]
-Breaking "original" already there blocks Causes Player aka client to Crash however player built blocks don't 
-Building cause considerable lag
-Minet Repeats what player says
-Text in chat doesn't display, only usernames
-Arrows burn when hitting ground

**Comment by NiclasOlofsson** [comment]
Would you mind explaining what this is "Minet Repeats what player says" thanks.

**Comment by NiclasOlofsson** [comment]
Fixed block breaks.Caused by changed packet structure in 0.11.
Text packet changed in 0.11. Need custom encoding/decoding.
Lag is because of light calculations on he client. Will see what can be done about that. It works better if loading anvil worlds with light already set for the blocks.
Arrow burning is fixed. This is caused by a new metadata type (long) that doesn't seem to work properly.

**Comment by PEMapModder** [comment]
@NiclasOlofsson about "Minet repeats what player says", it probably means the bug that the server sends the same packet a few times because client lag results in ACK being sent too slow. This problem exists in MCPE too.

**Comment by NiclasOlofsson** [comment]
Ah, ok. That also explains why it sends me massive amounts of resends on some operations, like break block. Sometimes i get 5-10 resends of all packets for that stuff. Hmm, that will kill performance, so I'd better compensate for that.

**Comment by NiclasOlofsson** [comment]
@PEMapModder did some investigation. It turns out that something is leaking on the iOS version of MCPE. I started getting more and more NAK, duplicate packets and crashes. Eventually the client was unusable. Restarting the whole iPad (hard reset) did the trick, and now it works good again. Seems to be leaking connections and all kinds of stuff. Actually looks like some sort of old school shared memory that is being reused between restarts of the actual client.
