### ISSUE TITLE
No logging when MiNET is started from a remote location.

### ISSUE THREAD

**Issue by 95CivicSi** [NiclasOlofsson/MiNET#417]
When starting MiNET from a location other than the directory that contains MiNET.Console.dll or the source project folder, MiNET does not appear to log anything to the console or in a log file.

For reference, normal startup message is similar to this:
```
Are you blessed with HW accelerated vectors? Yep!
Operations timed using the system's high-resolution performance counter.
  Timer frequency in ticks per second = 1000000000
  Timer is accurate within 1 nanoseconds
MiNET running. Press <enter> to stop service.
```

## Example 1 (Linux) :
 - Contents of minet-server.zip are located in `/home/user/servers/minet`
 - Console is in directory `/home/user/servers`
 - User executes command `dotnet ./minet/MiNET.Console.dll`
 - Server starts with initial startup message

### Results:
 - Users can join and use the server.
 - No information appears in the console except the initial startup message.
 - No log files are created.

## Example 2 (Windows) :
 - Contents of minet-server.zip are located in `D:\servers\minet`
 - User opens command prompt at `D:\servers`
 - User executes command `dotnet minet\MiNET.Console.dll`
 - Server starts with initial startup message

### Results: 
 - Users can join and use the server.
 - No information appears in the console except the initial startup message.
 - No log files are created.

**Comment by 95CivicSi** [comment]
Tested on version 1.0.1870

**Comment by NiclasOlofsson** [comment]
So it seems it can't find the configuration for log4net The problem would be related to this code:
```
			var logRepository = LogManager.GetRepository(Assembly.GetEntryAssembly());
			XmlConfigurator.Configure(logRepository, new FileInfo("log4net.xml"));

```
It tries to locate the file by taking the path of the executing assembly (basically where Main is) and then grab the file from the same location as that (which is where MiNET.Console.dll is located). What you can try to do is to copy the log4net.xml config into the directory where you start from (ie the working directory) and see if it can find the file then. Let me know how that works because if that's the case, it's a bit of a problem.

**Comment by 95CivicSi** [comment]
Copying log4net.xml, as you described, caused logs to to start working again.  It saves the logs in the same directory that the log4net.xml file is in.

**Comment by NiclasOlofsson** [comment]
Good to know. Reading the documentation about that on .NET Core doesn't make it any clearer to me. But when thinking a bit about it, the way it works is really fine to me since it would enable you to start servers with different configuration. I do wonder tho, does it also load the server.conf from the same directory?

**Comment by NiclasOlofsson** [comment]
@undrfined So here is the question; Should the files be read from where you are, or forced to where the binary is. I think my old unix brain says from "working directory" and not elsewhere.
But then my minecraft brain says "in a predicable directory" to not have to have support noobs not finding it every time.
Can't really decide.

**Comment by undrfined** [comment]
@NiclasOlofsson IMO there's no reason why it should be loaded from current working directory. Like, this is just config that you change once and forget about it. Can't really imagine any scenario where loading configs from working directory is better.

And yeah, easier for noobs :P

**Comment by NiclasOlofsson** [comment]
Ok, I will agree and take your PR then @undrfined
