### ISSUE TITLE
Please Add Plugins Support From PocketMine-MP

### ISSUE THREAD

**Issue by YaNIND** [NiclasOlofsson/MiNET#574]
pls add plugin support from pocketmine-mp

**Comment by NiclasOlofsson** [comment]
Ok. How do you want it to work?

**Comment by YaNIND** [comment]
pls add work all plugin from pocketmine, idk about C#

**Comment by kennyvv** [comment]
This isn't gonna be possible i'm afraid.

**Comment by YaNIND** [comment]
ok add apk MiNET in playstore

**Comment by dktapps** [comment]
This has the same energy as "please make pocketmine multicore"

**Comment by NiclasOlofsson** [comment]
Hey!

Thanks for writing in!

If you want to create your own server, please check out this page. https://www.minecraft.net/en-us/download/server

All community run servers are self-moderated. We are unable to answer any questions regarding any individual servers. This also means we do not ban or otherwise punish players on those servers.

For more information or if you have any questions, we recommend that you contact your server's administrators. Likewise, if you were banned from a server, you will need to contact that server’s support team to appeal the ban.

Best regards,
MiNET Team
